server:
  port: 52012

spring:
  application:
    name: whale-user
  cloud:
    nacos:
      discovery:
        server-addr: ${NACOS_HOST:127.0.0.1}:${NACOS_PORT:8848}
        namespace: ${NACOS_NAMESPACE:public}
        username: nacos
        password: nacos
      config:
        server-addr: ${spring.cloud.nacos.discovery.server-addr}
        namespace: ${NACOS_NAMESPACE:public}
        username: nacos
        password: nacos
  config:
    import:
      - optional:nacos:application.yml
      - optional:nacos:${spring.application.name}.yml